### PR TITLE
Fixing "Can not mount AppImage" error

### PR DESCRIPTION
**Pull request by FlorianBreuker**
Hello there!

I was experiencing following error on my Arch Linux machine:
image

When looking onto your AUR page. I came across the latest comment of superpupervlad who recommended adding 
!debug to the options tag in the MAKEPKG file. (source: https://gitlab.archlinux.org/pacman/pacman/-/issues/114)

After adding this tag to the MAKE file, I got the whole thing running again.

My fork just contains the !debug tag under options.

Hope to hear from you soon, and thanks for providing the AUR package.

Yours,
Florian

### CODE REVIEW

**Comment by elementh** [comment]
Hey there!

Thank you so much for your contribution! I'll try to upload the changes before the weekend, but they look good!

Glad the the package is of use to you :)

**Comment by FlorianBreuker** [comment]
Hello there,
just wanted to get a status update. 

I received a message from my colleague that his app image is no longer starting. It worked for him when I opened this pull request.

Have a great one.

**Comment by elementh** [comment]
Should be up!

**Comment by FlorianBreuker** [comment]
its working now with the AUR package.

thanks for your fast response:)

**Pull request merged**
